amps-kt/spa

- src/app/(protected)/[group]/[subGroup]/create-instance/form-section.tsx
- src/app/(protected)/[group]/[subGroup]/create-instance/page.tsx
- src/components/header.tsx
- src/lib/admin-panel.ts
- src/server/routers/user/index.ts
- src/server/routers/user/student/index.ts
- started working on basic crud procedures
- left form-section at stable state to move on
- restricted parts of the header UI based on role
> merge `crud` into main

- package.json
- prisma/schema.prisma
- src/app/(protected)/[group]/[subGroup]/[instance]/students/[id]/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/students/students-columns.tsx
- src/app/(protected)/[group]/[subGroup]/create-instance/form-section.tsx
- src/app/(protected)/[group]/[subGroup]/create-instance/page.tsx
- src/app/(protected)/[group]/[subGroup]/page.tsx
- src/app/(protected)/[group]/create-sub-group/form-section.tsx
- src/app/(protected)/[group]/create-sub-group/page.tsx
- src/app/(protected)/[group]/page.tsx
- src/app/(public)/[group]/[subGroup]/[instance]/projects/[id]/page.tsx
- src/app/api/trpc/[trpc]/route.ts
- src/lib/db/data.ts
- src/lib/db/seed.ts
- src/server/routers/institution/group.ts
- src/server/routers/institution/sub-group.ts
- src/server/routers/project.ts
- made many-to-many relationships explicit
- updated seed script to add mock preferences
- updated terminology on prisma model
- map prisma model attributes to snake_case version on db
> major schema and db refactor

- Makefile
- docker/docker-compose.override.yml
- docker/docker-compose.yml
Updated port number from 5432 to 6565 due to conflicting error with existing local database.
> Update port numbers.

- src/components/user-instances.tsx
changed order from group -> subGroup -> instance to instance -> subGroup -> group to emphasise that cards take you to an instance not a group
> updated user instances card UI

- src/components/user-instances.tsx
- src/styles/globals.css
Added scrollbar and padding to user instances component. Updated global.css file to include default styling for all scrollbars.
> Scrollbar added to user instances component on home page

- src/app/(protected)/[group]/[subGroup]/[instance]/(student)/my-allocation/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(student)/student-overview.tsx
- src/server/routers/institution/instance/matching.ts
Rank was correctly returned from the matching server and so did not require the `+1` before displaying on the frontend
> Fixed incorrect bug rank

- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-5)/manual-changes/_components/adjustment-row.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-5)/manual-changes/_components/allocation-store.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-5)/manual-changes/_components/row-removal-button.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-5)/manual-changes/_components/submit-button.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-5)/manual-changes/_components/unmatch-button.tsx
- src/lib/utils/allocation-adjustment/index.ts
- src/lib/utils/allocation-adjustment/project.ts
- src/lib/utils/allocation-adjustment/student.ts
**Completed**
- Updated adjustment row with new button to completely unmatch a student (remove their allocated project)
- Updated all functions ran onDragEnd to handle new cases
- Fetch updated data once the updating procedure is done running to update the internal state of the application
**TODO**
- add tooltip wrapper to unmatch and discard buttons
> [FEATURE] Ability to completely unmatch a student 

- src/app/(protected)/[group]/[subGroup]/[instance]/(student)/layout.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(student)/student-overview.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(supervisor)/supervisor-overview.tsx
- src/lib/utils/date/timezone.ts
- src/server/routers/user/student/index.ts
- src/server/routers/user/supervisor/index.ts
**Completed**
- Moved deadline offset computation to server
- Refactored datetime formatting function call
> [HOTFIX] Deadline timezone offset display

- src/lib/db/data/projects.ts
Removed "CS Joint Honours" flag from test data as all flags should start with either "MSci" or "BSc"
> [HOTFIX] Removed invalid flag from test data

- src/app/(protected)/[group]/[subGroup]/_components/form-button.tsx
- src/app/(protected)/[group]/[subGroup]/create-instance/page.tsx
- src/app/(protected)/[group]/[subGroup]/page.tsx
- src/app/(protected)/[group]/create-sub-group/_components/form-section.tsx
- src/app/(protected)/[group]/create-sub-group/page.tsx
- src/app/(protected)/[group]/page.tsx
- src/app/(protected)/admin/create-group/_components/form-section.tsx
- src/app/(protected)/admin/create-group/page.tsx
- src/components/access-control/admin-level-ac.tsx
- src/lib/validations/params.ts
- src/server/routers/institution/group.ts
- src/server/routers/institution/instance/index.ts
- src/server/routers/institution/sub-group.ts
- src/server/trpc.ts
- src/server/utils/admin-access.ts
**Completed**
- Improvements to code clarity in procedures
- Renamed procedures for internal consistency
- Standardised form UI across all space-creation pages
- Correctly pass input between middlewares
**TODO**
- Refactor remaining instance procedures
> [REFACTOR] Updated admin procedures + affected pages

- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-5)/manual-changes/_components/adjustment-row.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-5)/manual-changes/_components/project-card.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-5)/manual-changes/_components/row-removal-button.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-5)/manual-changes/_components/unmatch-button.tsx
- src/lib/db/data/index.ts
**Completed**
- Added tooltips to manual adjustment interface row actions
- Wrapped project cards in scrollbar
- Removed invalid flag from test data
> [HOTFIX] Minor UI improvements

- src/server/routers/institution/instance/algorithm/_utils/get-matching-data.ts
- src/server/routers/institution/instance/algorithm/index.ts
**Completed**
- filter preferences sent to allocation server based on the minimum and maximum preference list length restrictions
> [BUGFIX] Invalid length preference lists were sent to allocation server

- src/server/routers/institution/instance/_utils/fork.ts
- src/server/routers/institution/instance/_utils/instance-forking.ts
**Completed**
- Create the corresponding student details rows when forking an instance to allow proper project filtering and adding to preferences
> [BUGFIX] Create StudentDetails when forking an allocation instance

- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-5)/manual-changes/_components/matching-info-table.tsx
- src/components/instance-form.tsx
**Completed**
- fixed computation of matching info
- matches the information returned by the allocation server
- current implementation initialises a variable and updates it using the state in context
**TODO**
> [BUGFIX] Matching info was calculated incorrectly in manual-adjustment page

- src/app/layout.tsx
- src/components/breadcrumbs.tsx
- src/components/ui/breadcrumb.tsx
- src/server/routers/user/_utils/is-instance-path.ts
- src/server/routers/user/index.ts
**Completed**
- updated Breadcrumbs component
- added access control to group and sub-group route segments
> [BUGFIX] Improved breadcrumbs to restrict access to certain route segments based on user role

- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-1)/add-students/_components/csv-upload-button.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-1)/add-students/_components/form-section.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-1)/add-students/_components/new-student-columns.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-2)/supervisor-invites/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-3)/preference-submissions/_components/submissions-table.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-3)/student-invites/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-4)/algorithm-details/_components/details-columns.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-6)/allocation-overview/_components/by-project-columns.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-6)/allocation-overview/_components/by-student-columns.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-6)/allocation-overview/_components/by-student-data-table.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-6)/allocation-overview/_components/by-supervisor-columns.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-6)/allocation-overview/_components/by-supervisor-data-table.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-6)/export-to-csv/_components/allocation-columns.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-6)/export-to-csv/_components/export-button.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-6)/export-to-external-system/_components/check-students-section.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-6)/export-to-external-system/_components/check-users-section.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(supervisor)/my-allocations/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(supervisor)/my-projects/_components/my-projects-columns.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/students/_components/students-columns.tsx
- src/components/invite-table.tsx
- src/components/project-form.tsx
- src/lib/utils/external/matriculation.ts
- src/lib/validations/add-users/csv.ts
- src/lib/validations/allocation-csv-data.ts
- src/lib/validations/allocation-export-data.ts
- src/server/routers/institution/instance/external/index.ts
- src/server/routers/institution/instance/matching.ts
**Completed** 
- replaced all uses of student matriculation number as unique identifier in the system with student GUID
- only convert to matriculation number before export to external system
> [HOTFIX] Use student GUID as main identifier in system

- src/lib/db/data/index.ts
- src/lib/db/data/preferences.ts
- src/lib/db/data/projects.ts
**Completed**
- added `specialTechnicalRequirements` to some projects
- replaced hard-coded flags and tags with references to the test data definitions
- added two more preferences to the student evaluator's preference list
> [HOTFIX] Updated test data

- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-4)/algorithms-overview/page.tsx
- src/server/routers/user/index.ts
**Completed**
- Fixed minor bug in adminPanelRoute procedure
- Removed custom algorithms section from demo as the validation of matchings seems to be unstable
**TODO**
> [HOTFIX] Minot bugfix + remove custom Algorithms from demo

- src/server/routers/institution/instance/algorithm/_utils/extract-matching-details.ts
- src/server/routers/institution/instance/algorithm/index.ts
**Completed**
- filter unmatched projects from data supplied to details table
- check projectId in formatting function
**TODO**
- validate server matching response before sending to app
> [BUGFIX] Temporary fix for details tables

- src/app/(protected)/[group]/[subGroup]/[instance]/(supervisor)/layout.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(supervisor)/new-project/_components/create-project-form.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(supervisor)/new-project/page.tsx
- src/components/project-form.tsx
- src/server/routers/project/index.ts
Updated new project page stage to display error if stage is greater than stage 3 - project selection.
Updated project form to only allow student defined projects at stage 2
> [FEATURE] supervisors can submit project at stage 3

- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-4)/algorithm-details/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-4)/algorithms-overview/_components/run-algorithm-button.tsx
- src/server/routers/institution/instance/algorithm/_utils/extract-matching-details.ts
- src/server/routers/institution/instance/algorithm/index.ts
**Completed**
- Refactored procedure for fetching matching details to client
- filter out unmatched projects before extracting matching details
> [BUGFIX] Matching details table caused runtime error 

- src/app/(protected)/[group]/[subGroup]/[instance]/layout.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/not-found.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/projects/[id]/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/students/[id]/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/supervisors/[id]/page.tsx
- src/app/(protected)/[group]/[subGroup]/page.tsx
- src/app/(protected)/[group]/create-sub-group/page.tsx
- src/app/(protected)/[group]/page.tsx
- src/app/not-found.tsx
- src/components/params-context.tsx
- src/server/routers/institution/group.ts
- src/server/routers/institution/instance/index.ts
- src/server/routers/institution/sub-group.ts
- src/server/routers/project/index.ts
- src/server/routers/user/student/index.ts
- src/server/routers/user/supervisor/index.ts
**Completed**
- created procedures to check if the object exists in the database
- added guards at every dynamically generated page and if the expected object does not exist redirect to either the root or instance `not-found` pages
> [FEATURE] Created custom 404 page

- src/app/(protected)/[group]/[subGroup]/_components/form-button.tsx
- src/app/(protected)/[group]/_components/form-button.tsx
- src/app/(protected)/[group]/create-sub-group/_components/form-section.tsx
- src/app/(protected)/admin/create-group/_components/form-section.tsx
- src/components/breadcrumbs.tsx
- src/lib/auth/auth.config.ts
- src/lib/db/data/index.ts
- src/lib/validations/add-admins/new-admin.ts
- src/lib/validations/breadcrumbs.ts
- src/lib/validations/instance-tabs.ts
- src/server/routers/institution/group.ts
- src/server/routers/institution/instance/index.ts
- src/server/routers/institution/sub-group.ts
- src/server/routers/user/_utils/user-breadcrumbs.ts
- src/server/routers/user/index.ts
- src/server/utils/admin-access.ts
- src/server/utils/is-group-admin.ts
- src/server/utils/is-sub-group-admin.ts
**Completed**
- updated admin panel forms (improvements to validation logic and error handling)
- updated test data to work with changes to admin
- created new breadcrumb segment validator procedure
> [REFACTOR] Improved admin access control

- prisma/schema.prisma
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-3)/late-proposals/_components/late-project-data-table.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-3)/late-proposals/_components/late-projects-columns.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-3)/late-proposals/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(supervisor)/my-projects/_components/my-projects-columns.tsx
- src/lib/db/data/index.ts
- src/lib/validations/admin-panel-tabs.ts
- src/lib/validations/dto/project.ts
- src/server/routers/institution/instance/_utils/instance-forking.ts
- src/server/routers/institution/instance/_utils/merge.ts
- src/server/routers/project/index.ts
**Completed**
- added latestEditDateTime to project db model which updates whenever a project is edited
- created new page in stage 3 for displaying late proposals
- created new procedure for fetching late proposals
- created new data table for displaying late proposals
- minor improvements to my-projects data table
- made sure that when a project is forked, the latestEditDateTime is carried over so that the projects aren't automatically flagged as late proposals
> [FEATURE] Created Late project proposals panel

- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-1)/add-students/_components/csv-upload-button.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-1)/add-students/_components/new-student-columns.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-1)/add-students/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-1)/add-supervisors/_components/csv-upload-button.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-1)/add-supervisors/_components/new-supervisor-columns.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-1)/add-supervisors/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-3)/preference-submissions/_components/submissions-table.tsx
- src/components/breadcrumbs.tsx
- src/components/toast-card/csv-parsing-error.tsx
- src/components/toast-card/user-creation-error.tsx
- src/lib/utils/csv/parse-for-duplicates.ts
- src/lib/utils/general/find-duplicates.ts
- src/lib/utils/general/result.ts
- src/server/routers/institution/instance/_utils/add-students-transaction.ts
- src/server/routers/institution/instance/_utils/add-supervisors-transaction.ts
- src/server/routers/institution/instance/_utils/check-users-membership.ts
- src/server/routers/institution/instance/index.ts
- src/server/routers/institution/instance/project.ts
- src/server/utils/id-email-check.ts
**Fixed mass upload validation**
- created check-users-membership util function that creates a validation pipeline for checking if users are members of an instance, exist in the system or are have an email already associated with another account
- created Result type for handling success and error states in the validation pipeline
- created add-students-transaction util function that creates a transaction for adding students to an instance using the check-users-membership util function
- created add-supervisors-transaction util function that creates a transaction for adding supervisors to an instance using the check-users-membership util function
- updated the add-students and add-supervisors pages to use the updated transaction procedures
- created new Error toast card for user creation …
> [BUGFIX] Mass upload via CSV validates users correctly

- src/components/header/user-button.tsx
- src/lib/auth/procedures.ts
- src/lib/utils/general/blank-email.ts
- src/server/utils/id-email-check.ts
**Completed**
- If a user has an empty email address, and someone adds them as a supervisor but with an email address, update their email address.
Closes issue #172
> [HOTFIX] Update email address if old is blank

- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/supervisor-tasks/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(student)/layout.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(student)/my-preferences/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(student)/student-overview.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(supervisor)/layout.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(supervisor)/supervisor-overview.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/supervisors/layout.tsx
- src/components/join-instance.tsx
- src/lib/validations/role/index.ts
- src/lib/validations/tabs/admin-panel.ts
- src/server/routers/user/_utils/get-self-defined-project.ts
- src/server/routers/user/index.ts
- src/server/utils/admin/access.ts
- src/server/utils/admin/is-super-admin.ts
- src/server/utils/instance/user-role.ts
**Completed**
- Created component for setting users invite status to "joined".
- Refactored getAllUserRoles util to return a set.
- Refactored some utils to accept TransactionClient for operations.
> [HOTFIX] Users marked as joined when first accessing the platform

- src/lib/auth/procedures.ts
- src/lib/utils/date/now.ts
- src/lib/validations/auth.ts
- src/server/routers/institution/instance/index.ts
- src/server/routers/user/_utils/user-breadcrumbs.ts
- src/server/trpc.ts
- src/server/utils/id-email-check.ts
- src/server/utils/instance/user-role.ts
**Completed**
- updated the method for getting user roles
- breadcrumb roles checks now take multiple roles into account
- enabled email collection of users who access the site before being invited
Closes #180
> [BUGFIX] Breadcrumbs bug when usr has multiple roles

- src/components/kanban-board/project-preference-card.tsx
- src/lib/utils/csv/use-csv-download.ts
**Completed**
- fixed bug in "My Preferences" page in displaying longer project titles
- fixed CSV download button
> [HOTFIX] Minor UI issues in Project Selection stage

- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-3)/late-proposals/_components/late-projects-columns.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-6)/allocation-overview/_components/by-project-columns.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-6)/export-to-csv/_components/allocation-columns.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-6)/export-to-csv/_components/export-button.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(supervisor)/my-projects/_components/my-projects-columns.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/projects/_components/all-projects-columns.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/supervisors/[id]/_components/supervisor-projects-columns.tsx
- src/lib/validations/allocation-csv-data.ts
- src/lib/validations/tabs/admin-panel.ts
- src/server/routers/institution/instance/matching.ts
**Completed**
Closes #178 
- refactored procedure to include supervisor data
- decoupled ui from db model
- refactored export button to use existing reusable component
> [FEATURE] Added supervisor data to stage 6 data export csv

- prisma/schema.prisma
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-3)/late-proposals/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-3)/preference-submissions/_components/preference-submissions-columns.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-3)/preference-submissions/_components/preference-submissions-data-table.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-3)/preference-submissions/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-3)/student-invites/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/projects/[id]/_components/student-preference-columns.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/projects/[id]/_components/student-preference-data-table.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/projects/[id]/page.tsx
- src/components/copy-emails-button.tsx.tsx
- src/lib/utils/preferences/sort.ts
- src/lib/validations/dto/preference.ts
- src/lib/validations/instance-form.ts
- src/server/routers/institution/instance/_utils/pre-allocated-students.ts
- src/server/routers/institution/instance/index.ts
- src/server/routers/institution/instance/project.ts
- src/server/routers/project/index.ts
- src/server/routers/user/student/preference.ts
Closes #214 
- "Preference Submissions" and "Student Invites" pages now correctly omit pre-allocated students from the copy emails list
- created a student preference section on project pages for displaying the students who have the particular project saved to their preference lists
> [FEATURE] Student preference improvements

- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-1)/add-students/_components/add-students-section.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-1)/add-students/_components/new-student-columns.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-1)/add-students/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-1)/add-supervisors/_components/add-supervisors-section.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-1)/add-supervisors/_components/new-supervisor-columns.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-1)/add-supervisors/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-1)/layout.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-2)/project-submissions/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-2)/supervisor-invites/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-6)/export-to-csv/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-6)/fork-instance/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-6)/merge-instance/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(student)/my-allocation/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/projects/page.tsx
- src/lib/validations/tabs/admin-panel.ts
- src/server/routers/institution/instance/index.ts
Closes #219 
- ability to add users at stage 2 and stage 3
- access-controlled user removal to only be allowed in stage 1
> [FEATURE] Add users to  Instance in later stages

- package.json
- pnpm-lock.yaml
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-4)/preference-statistics/_components/download-preference-section.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-4)/preference-statistics/_components/download-zip-file-button.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-4)/preference-statistics/page.tsx
- src/components/export-csv.tsx
- src/components/side-panel/icons.tsx
- src/content/pages/index.ts
- src/lib/utils/general/instance-params.ts
- src/lib/validations/dto/preference.ts
- src/lib/validations/tabs/instance.ts
- src/lib/validations/tabs/side-panel.ts
- src/server/routers/institution/instance/index.ts
- src/server/routers/institution/instance/preference/_utils/generate-csv-data.ts
- src/server/routers/institution/instance/preference/index.ts
- src/server/routers/user/_utils/user-breadcrumbs.ts
**Completed**
- created page for downloading preference statistics
- created new preference router for centralising preference related procedures
- moved `getTabs` util to side-panel file
- created new utils for generating csv data
- created new util for expanding instance params
> [FEATURE] Admin can download student preference statistics

- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-4)/algorithms/_components/algorithm-columns.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-4)/algorithms/_components/algorithm-context.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-4)/algorithms/_components/algorithm-data-table.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-4)/algorithms/_components/algorithm-result-columns.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-4)/algorithms/_components/algorithm-result-data-table.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-4)/algorithms/_components/clear-results-section.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-4)/algorithms/_components/new-algorithm-section.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-4)/algorithms/_components/run-algorithm-button.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-4)/algorithms/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-4)/results/_components/student-results-section.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-5)/manual-changes/_components/submit-button.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/settings/_components/delete-confirmation.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/settings/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/layout.tsx
- src/components/danger-zone.tsx
- src/components/params-context.tsx
- src/components/ui/carousel.tsx
- src/components/ui/data-table/data-table-context.tsx
- src/server/routers/institution/instance/index.ts
- src/server/routers/institution/instance/matching.ts
- src/server/routers/institution/instance/preference/index.ts
- added section for clearing results in the algorithm page
- created procedures to clear results
- created context for handling selected algorithm
> [FEATURE] Ability to reset stage 4 data

- package.json
- pnpm-lock.yaml
- prisma/schema.prisma
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-2)/pre-allocated-projects/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-4)/preference-statistics/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-6)/manage-user-access/_components/student-access-toggle.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-6)/manage-user-access/_components/supervisor-access-toggle.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-6)/manage-user-access/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(student)/my-allocation/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(student)/student-overview.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(supervisor)/my-allocations/page.tsx
- src/components/pages/supervisor-instance-home.tsx
- src/components/side-panel/icons.tsx
- src/content/pages/index.ts
- src/lib/auth/procedures.ts
- src/lib/validations/tabs/side-panel.ts
- src/server/routers/user/student/index.ts
- src/server/routers/user/supervisor/index.ts
Closes #223 
- create new page for managing user's access to the final allocation in stage 6
- updated allocationInstance data model to contain this information
- created procedures to get/set the access by student/supervisor
- added Metadata to all new pages
> [FEATURE] Granular access control to allocation results in stage 6

- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-4)/results/_components/student-results-columns.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-4)/results/_components/supervisor-results-columns.tsx
- src/components/kanban-board/project-preference-card.tsx
- src/components/student-saved-preferences/columns.tsx
- src/components/student-saved-preferences/data-table.tsx
- src/lib/utils/permissions/stage-check.ts
- src/server/routers/user/student/preference.ts
- student results supervisor link was broken
- supervisor result columns were not sorting properly
- removed project preference card handle in stages >= 4
- updated RBAC in saved preference columns
- created a new function to check if a stage is within a range
> [HOTFIX] Minor bug fixes

- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-3)/preference-submissions/_components/summary-section.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-3)/preference-submissions/page.tsx
- src/components/ui/data-table/data-table-pagination.tsx
- src/lib/validations/algorithm.ts
- src/server/routers/institution/instance/algorithm/index.ts
- created simple summary section in preference submissions page
- negate allocation - target difference in supervisor results
- fix data table pagination component selection bug
> [HOTFIX] Minor UI fixes

- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-6)/export-to-csv/_components/allocation-columns.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-6)/export-to-csv/_components/export-button.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(student)/my-allocation/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(supervisor)/my-allocations/_components/allocation-card.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(supervisor)/my-allocations/page.tsx
- src/components/copy-email-link.tsx
- src/lib/validations/allocation-csv-data.ts
- src/server/routers/institution/instance/matching.ts
- src/server/routers/user/student/index.ts
- src/server/routers/user/supervisor/index.ts
Closes #246 
- Fixed early access to allocation bug
- Improvements to UI displaying allocation to users
- added user emails to CSV export
> [BUG] Fixed bug that gave students access to allocation at the same time as supervisors

- .github/workflows/publish.yml
Follow the way that https://docs.docker.com/build/ci/github-actions/manage-tags-labels/ handles multiple tags
> prevent invalid tag issues

- src/components/header/admin-panel-button.tsx
do not show button if user does not have admin panels
> hotfix:admin panel button visible to admins only

- docker/docker-compose.prod.yml
- docker/docker-compose.staging.yml
- src/env.ts
I finally got around to dropping the env vars, so here are the proper compose files for both prod and staging; 
I haven't properly tested the prod stuff - because I can't do that on my local machine. I need the proxy setup.
May also be worth writing some more documentation - let me know what you think.
> Ops: setup proper docker compose files for staging and prod

- prisma/schema/algorithm.prisma
- prisma/schema/index.prisma
- prisma/schema/marking.prisma
- prisma/schema/project.prisma
- prisma/schema/user.prisma
The whole data-model rework is going to be pretty substantial, so I've decided to try and break it up. First I want to get approval on the relation renamings I've done here. I'll think about how to attack some of the other things later once I've spoken some more to Yiannis and Paul.
> qol: Rename prisma relations

- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-specific)/(stage-1)/all-students/[id]/_components/student-preferences-section.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-specific)/(stage-1)/all-students/[id]/preferences/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-specific)/(stage-4)/algorithms/_components/algorithm-data-table.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-specific)/(stage-4)/algorithms/_components/algorithm-result-data-table.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-specific)/(stage-4)/results/_components/student-results-section.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-specific)/(stage-4)/results/_components/supervisor-results-data-table.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-specific)/(stage-4)/results/_components/supervisor-results-section.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-specific)/(stage-6)/allocation-overview/page.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(student)/my-preferences/page.tsx
- src/components/instance-wizard/marking-scheme-builder/centre-panel.tsx
- src/components/ui/data-table/data-table.tsx
- src/components/ui/data-table/hooks/add-prefix.ts
- src/components/ui/data-table/hooks/column-filter.ts
- src/components/ui/data-table/hooks/global-filter.ts
- src/components/ui/data-table/hooks/pagination.ts
- src/components/ui/data-table/hooks/row-selection.ts
- src/components/ui/data-table/hooks/sorting.ts
- src/components/ui/data-table/hooks/visibility.ts
- src/components/ui/tabs.tsx
- **added tab state to url**
- **added search param prefix option to data table**
- **added prefix to data tables which share pages**
> feat: Search Param State

- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-specific)/(stage-1)/add-supervisors/_components/add-supervisors-section.tsx
- src/app/(protected)/[group]/[subGroup]/[instance]/(admin-panel)/(stage-specific)/(stage-1)/all-supervisors/_components/all-supervisors-data-table.tsx
- src/server/middleware.ts
- src/server/routers/institution/instance/index.ts
- src/server/routers/user/supervisor/index.ts
- replaced UserInInstance deletion op with SupervisorDetails deletion op
- moved supervisor deletion logic to instance router
- added stage check to UserInInstance deletion op
> bugfix: can now remove supervisors up to and including Stage 4

- src/data-objects/space/instance.ts
Just a one line change to fix this.
> bugfix: Manual allocation
